### ISSUE TITLE
USER STORY: creating a clear nav bar that links to each page on the website

### ISSUE THREAD

**Issue by judewoolls** [judewoolls/first-project-prep#1]
**User persona**

 I am a young person trying to quickly find the content i am looking for.

**Acceptance criteria**

- [ ] A clear nav bar with a link for each section
- [ ] The nav bar has clear text
- [ ] Nav bar displays the branding of the website

**Tasks**

- [ ] Create a navbar using bootstrap and html
- [ ] use a tags with a href to the id of a section of the page or the relevant file
- [ ] Choose a color scheme that uses contrast
- [ ] Nav bar uses the main header font
