### ISSUE TITLE
USER STORY: Page of resources and places to contact professionals

### ISSUE THREAD

**Issue by judewoolls** [judewoolls/first-project-prep#2]
**User persona**
A distressed person who is struggling and looking for ways to contact mental health professionals

**Acceptance Criteria**

- [ ] navbar and footer are the same as the rest of the site
- [ ] A clear page of sections for online therapists, in-person therapists and groups to attend
- [ ] Clear headings for each section
- [ ] Description of each section

**Tasks**

- [ ] create a html page for the support section
- [ ] include the nav bar and footer
- [ ] add ai image to each section next to the descriptions
- [ ] make page responsive using bootstrap
